# Generated by Django 5.0.4 on 2024-04-20 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesnetworkobject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='salesnetworkobject',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='sales_network.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='salesnetworkobject',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.salesnetworkobject', verbose_name='Поставщик'),
        ),
    ]
