# Generated by Django 5.0.4 on 2024-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesnetworkobject',
            name='products',
            field=models.ManyToManyField(blank=True, to='sales_network.product', verbose_name='Продукты'),
        ),
    ]
